FROM hadoop-base:3.3.6

LABEL maintainer="Rohan Rajbanshi <rohanrajbanshi1@gmail.com>"

HEALTHCHECK CMD curl -f http://localhost:8088/ || exit 1

ADD run.sh /run.sh
RUN chmod a+x /run.sh

EXPOSE 8088

CMD ["/run.sh"]
